CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(256) NOT NULL UNIQUE ,
    password VARCHAR(256) NOT NULL,
    view_name VARCHAR(256) NOT NULL,
    role_type ENUM('ADMIN','USER') NOT NULL
);

CREATE TABLE category (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE news(
    id    BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(256) NOT NULL,
    body  LONGTEXT,
    category_id BIGINT NOT NULL,
    publish_at DATETIME,
    create_at DATETIME DEFAULT NOW(),
    user_id BIGINT NOT NULL
);